apiVersion: v1
kind: Secret
metadata:
  name: portal-secret
  namespace: student-portal
type: Opaque
stringData:
  POSTGRES_PASSWORD: portalpass
  DATABASE_URL: postgresql://portaluser:portalpass@postgres:5432/studentportal
